"""empty message

Revision ID: 0dad482280ab
Revises: edc126de685d
Create Date: 2021-07-10 17:02:35.028142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dad482280ab'
down_revision = 'edc126de685d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='character')
    op.drop_index('id_2', table_name='character')
    op.drop_constraint('character_ibfk_1', 'character', type_='foreignkey')
    op.drop_column('character', 'favorite_characters_id')
    op.drop_index('id', table_name='planet')
    op.drop_index('id_2', table_name='planet')
    op.drop_constraint('planet_ibfk_1', 'planet', type_='foreignkey')
    op.drop_column('planet', 'favorite_planets_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('favorite_planets_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('planet_ibfk_1', 'planet', 'favoritePlanets', ['favorite_planets_id'], ['id'])
    op.create_index('id_2', 'planet', ['id'], unique=False)
    op.create_index('id', 'planet', ['id'], unique=False)
    op.add_column('character', sa.Column('favorite_characters_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('character_ibfk_1', 'character', 'favoriteCharacters', ['favorite_characters_id'], ['id'])
    op.create_index('id_2', 'character', ['id'], unique=False)
    op.create_index('id', 'character', ['id'], unique=False)
    # ### end Alembic commands ###
