"""empty message

Revision ID: 477a12938809
Revises: be3a149bbf64
Create Date: 2021-07-10 19:38:45.934037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477a12938809'
down_revision = 'be3a149bbf64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favoritePlanets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('favoritePlanets', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favoritePlanets', 'planets', ['planet_id'], ['id'])
    op.create_foreign_key(None, 'favoritePlanets', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoritePlanets', type_='foreignkey')
    op.drop_constraint(None, 'favoritePlanets', type_='foreignkey')
    op.drop_column('favoritePlanets', 'planet_id')
    op.drop_column('favoritePlanets', 'user_id')
    # ### end Alembic commands ###
