"""empty message

Revision ID: 566d7042aaf7
Revises: 45be6038ba39
Create Date: 2021-07-10 15:26:06.008175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '566d7042aaf7'
down_revision = '45be6038ba39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favoriteCharacters_ibfk_2', 'favoriteCharacters', type_='foreignkey')
    op.drop_constraint('favoriteCharacters_ibfk_1', 'favoriteCharacters', type_='foreignkey')
    op.drop_column('favoriteCharacters', 'character_id')
    op.drop_column('favoriteCharacters', 'user_id')
    op.add_column('user', sa.Column('favorite_characters', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'favoriteCharacters', ['favorite_characters'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'favorite_characters')
    op.add_column('favoriteCharacters', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('favoriteCharacters', sa.Column('character_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('favoriteCharacters_ibfk_1', 'favoriteCharacters', 'character', ['character_id'], ['id'])
    op.create_foreign_key('favoriteCharacters_ibfk_2', 'favoriteCharacters', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
