"""empty message

Revision ID: 9c54528de782
Revises: 3ec66e73b46f
Create Date: 2021-07-10 17:07:15.588170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c54528de782'
down_revision = '3ec66e73b46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'gender')
    op.drop_column('character', 'eye_color')
    op.drop_column('character', 'edited')
    op.drop_column('character', 'birth_year')
    op.drop_column('character', 'created')
    op.drop_column('character', 'height')
    op.drop_column('character', 'mass')
    op.drop_column('character', 'hair_color')
    op.drop_column('character', 'homeword')
    op.drop_column('character', 'url')
    op.drop_column('character', 'skin_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('skin_color', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('character', sa.Column('url', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('character', sa.Column('homeword', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('character', sa.Column('hair_color', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('character', sa.Column('mass', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('character', sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('character', sa.Column('created', mysql.DATETIME(), nullable=True))
    op.add_column('character', sa.Column('birth_year', mysql.DATETIME(), nullable=True))
    op.add_column('character', sa.Column('edited', mysql.DATETIME(), nullable=True))
    op.add_column('character', sa.Column('eye_color', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('character', sa.Column('gender', mysql.VARCHAR(length=45), nullable=True))
    # ### end Alembic commands ###
