"""empty message

Revision ID: be3a149bbf64
Revises: 0aa7c993ad66
Create Date: 2021-07-10 18:30:01.960715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be3a149bbf64'
down_revision = '0aa7c993ad66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'terrain')
    op.drop_column('planets', 'url')
    op.drop_column('planets', 'surface_water')
    op.drop_column('planets', 'created')
    op.drop_column('planets', 'climate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('climate', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('planets', sa.Column('created', mysql.DATETIME(), nullable=True))
    op.add_column('planets', sa.Column('surface_water', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('planets', sa.Column('url', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('planets', sa.Column('terrain', mysql.VARCHAR(length=45), nullable=True))
    # ### end Alembic commands ###
