"""empty message

Revision ID: d028dea4afc8
Revises: 544cbd9383f6
Create Date: 2021-07-10 17:32:37.024790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd028dea4afc8'
down_revision = '544cbd9383f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('race', sa.String(length=250), nullable=True))
    op.add_column('characters', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('birth', sa.String(length=250), nullable=True))
    op.add_column('characters', sa.Column('sex', sa.String(length=250), nullable=True))
    op.add_column('characters', sa.Column('country', sa.String(length=250), nullable=True))
    op.drop_column('characters', 'orbital_period')
    op.drop_column('characters', 'diameter')
    op.drop_column('characters', 'surface_water')
    op.drop_column('characters', 'created')
    op.drop_column('characters', 'rotation_planet')
    op.drop_column('characters', 'terrain')
    op.drop_column('characters', 'gravity')
    op.drop_column('characters', 'population')
    op.drop_column('characters', 'url')
    op.drop_column('characters', 'climate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('climate', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('characters', sa.Column('url', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('characters', sa.Column('population', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('gravity', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('terrain', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('characters', sa.Column('rotation_planet', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('created', mysql.DATETIME(), nullable=True))
    op.add_column('characters', sa.Column('surface_water', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('diameter', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('orbital_period', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('characters', 'country')
    op.drop_column('characters', 'sex')
    op.drop_column('characters', 'birth')
    op.drop_column('characters', 'age')
    op.drop_column('characters', 'race')
    # ### end Alembic commands ###
