"""empty message

Revision ID: edc126de685d
Revises: 566d7042aaf7
Create Date: 2021-07-10 16:47:00.838144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edc126de685d'
down_revision = '566d7042aaf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('favorite_characters_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'character', 'favoriteCharacters', ['favorite_characters_id'], ['id'])
    op.drop_index('id', table_name='favoriteCharacters')
    op.drop_index('id_2', table_name='favoriteCharacters')
    op.drop_constraint('favoritePlanets_ibfk_1', 'favoritePlanets', type_='foreignkey')
    op.drop_constraint('favoritePlanets_ibfk_2', 'favoritePlanets', type_='foreignkey')
    op.drop_column('favoritePlanets', 'user_id')
    op.drop_column('favoritePlanets', 'planet_id')
    op.add_column('planet', sa.Column('favorite_planets_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planet', 'favoritePlanets', ['favorite_planets_id'], ['id'])
    op.add_column('user', sa.Column('favorite_planets', sa.Integer(), nullable=True))
    op.alter_column('user', 'favorite_characters',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'user', 'favoritePlanets', ['favorite_planets'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('user', 'favorite_characters',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('user', 'favorite_planets')
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.drop_column('planet', 'favorite_planets_id')
    op.add_column('favoritePlanets', sa.Column('planet_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('favoritePlanets', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('favoritePlanets_ibfk_2', 'favoritePlanets', 'user', ['user_id'], ['id'])
    op.create_foreign_key('favoritePlanets_ibfk_1', 'favoritePlanets', 'planet', ['planet_id'], ['id'])
    op.create_index('id_2', 'favoriteCharacters', ['id'], unique=False)
    op.create_index('id', 'favoriteCharacters', ['id'], unique=False)
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_column('character', 'favorite_characters_id')
    # ### end Alembic commands ###
